### ISSUE TITLE
https://2023.ploneconf.org/ redirects to 2015

### ISSUE THREAD

**Issue by stevepiercy** [plone/ploneconf.org#79]
https://2023.ploneconf.org/ redirects to 2015, or sometimes does not respond.

**Comment by tkimnguyen** [comment]
I don't think this is still happening, and I don't think anyone else reported it once we started using the site heavily

**Comment by stevepiercy** [comment]
I don't think the number of visitors would affect redirects.

Whoever configures the redirect for `ploneconf.org` to `yyyy.ploneconf.org` should include this item in their checklist for 2024. I'd suggest keeping this issue open for whoever that may be.

**Comment by tkimnguyen** [comment]
I don't understand; what does the redirect of ploneconf.org have to do with 2023.ploneconf.org redirecting to 2015.ploneconf.org?

**Comment by stevepiercy** [comment]
The configuration for the redirect of `2023.ploneconf.org` was fixed.

However, for the last two years, the redirect of the naked domain `ploneconf.org` has been a forgotten configuration item, continuing to point at the previous conference year.

Additionally when someone attempts to visit `2024.ploneconf.org`, there is a configuration item (not sure where) that redirects the upcoming conference year to the first listed domain of `2015.ploneconf.org`. I think that is a default nginx configuration item.

I'm not on the AI team, so I don't know the details of DNS and nginx configuration.

**Comment by tkimnguyen** [comment]
Ok thanks. I'll create separate issues then
